services:
  gpu4_batch2:
    image: jupyter-jax:v2
    user: root    
    devices:
      - /dev/kfd
      # - /dev/dri
      - /dev/dri/renderD160 
      - /dev/dri/renderD168 
      - /dev/dri/renderD184 
      - /dev/dri/renderD176
    security_opt:
      - seccomp=unconfined
    volumes:
      - /mnt/nvme0/data/:/data 
      - /mnt/nvme0/hf-models/gemma-ua-spm/:/tokenizer
      - /mnt/nvme0/hf-datasets/:/hf-datasets
      - /mnt/nvme0/h5-models/:/ckpts
      - /mnt/nvme0/output/:/output
      - /home/antp/hybrid-infra/zapier-eval:/content
      - /tmp/:/tmp
      - /tmp/.cache:/root/.cache
    ports:
      - 38888:8888
    tty: true
    stdin_open: true
    working_dir: /content
    command: >
      sh -c "
        jupyter notebook --port 8888 --token colabToken --allow-root --no-browser --ip=0.0.0.0 --NotebookApp.token=colabToken 
      "